name: comment-on-pr example
on: pull_request
jobs:
  example:
    name: sample comment
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN_READ }}
        with:
          msg: "Preview will be available @ https://pr-${{ github.event.pull_request.number }}.d2cghdht4ghu4n.amplifyapp.com"