name: Send SMS on Pull Request

on: [pull_request]

jobs:
  sms:

    runs-on: ubuntu-latest

    steps:
    - name: 'Sending SMS Notification'
      uses: twilio-labs/actions-sms@v1
      with:
        fromPhoneNumber: '+12039025279'
        toPhoneNumber: '+49(176)32630997'
        message: 'Pull Request to Repo Donskelle/Me check it out at https://github.com/Donskelle/me/pulls'
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
